services:
  product-service:
    build: .
    ports:
      - "5001:5001"
    environment:
      DB_HOST: host.docker.internal
      DB_PORT: 5432
      DB_NAME: ecommerce
      DB_USER: postgres
      DB_PASSWORD: postgres
