apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: dev
  labels:
    app: product-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: zhehaochen/product-service:IMAGE_TAG_PLACEHOLDER
          imagePullPolicy: Always
          ports:
            - containerPort: 5001
          envFrom:
            - configMapRef:
                name: product-service-config
            - secretRef:
                name: postgres-secret
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: dev
spec:
  selector:
    app: product-service
  ports:
    - port: 5001
      targetPort: 5001
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: product-service-nodeport
  namespace: dev
spec:
  selector:
    app: product-service
  ports:
    - port: 5001
      targetPort: 5001
      nodePort: 30001
  type: NodePort
